WPEFRAMEWORK_LAUNCHER_VERSION = 77411508b433ce9955b02d6c1ca02c4ba8f553ee
WPEFRAMEWORK_LAUNCHER_SITE = $(call github,WebPlatformForEmbedded,WPEPluginLauncher,$(WPEFRAMEWORK_LAUNCHER_VERSION))
WPEFRAMEWORK_LAUNCHER_INSTALL_STAGING = YES
WPEFRAMEWORK_LAUNCHER_DEPENDENCIES = wpeframework wpeframework-interfaces

WPEFRAMEWORK_LAUNCHER_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_LAUNCHER_VERSION}

$(eval $(cmake-package))

