WPEFRAMEWORK_SWITCHBOARD_VERSION = 050a6631ab665d4137c7d7d5647e7a31e8918cbb
WPEFRAMEWORK_SWITCHBOARD_SITE_METHOD = git
WPEFRAMEWORK_SWITCHBOARD_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SWITCHBOARD_INSTALL_STAGING = YES
WPEFRAMEWORK_SWITCHBOARD_DEPENDENCIES = wpeframework

WPEFRAMEWORK_SWITCHBOARD_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_SWITCHBOARD_VERSION}

$(eval $(cmake-package))

