#!/bin/sh

# Reset the console
/usr/bin/reset

# Stop the gravity sensor if it's loaded
if [ -x /usr/sbin/gsensor ] ; then
	/usr/sbin/gsensor --stop
fi

# Check that the screen is available. If not, wait until the
# user presses START/ENTER in the VT console.
while /bin/true; do
	fuser /dev/dri/by-path/platform-13050000.lcd-controller-card >/dev/null
	[ $? -eq 1 ] && break
	read
done

# Reset clock frequency to the default one
if [ -r /var/tmp/boot_cpu_freq ] ; then
	cat /var/tmp/boot_cpu_freq > /sys/devices/system/cpu/cpu0/cpufreq/scaling_setspeed
fi

# Restore the loading splash if needed
if [ `cat /sys/class/vtconsole/vtcon1/bind` -ne 0 -o ! -f /var/tmp/.boot_complete ] ; then
	touch /var/tmp/.boot_complete

	if [ -r /usr/local/share/opendingux/loading.png ] ; then
		fbsplash /usr/local/share/opendingux/loading.png
	else
		fbsplash /usr/share/opendingux/loading.png
	fi
fi

if [ -x ~/.autostart ]; then
	exec ~/.autostart
else
	exec /usr/bin/gmenu2x
fi
