#!/bin/sh

if [ -t 0 ] ; then
	read -sp 'New password: ' R_PASSWD
	read -sp 'Repeat password: ' R_PASSWD2

	if [ -z "$R_PASSWD" ] ; then
		echo 'Empty password entered, aborting.'
		exit 1
	fi

	if [ "$R_PASSWD" != "$R_PASSWD2" ] ; then
		echo "Passwords don't match, aborting."
		exit 1
	fi

	sed -i -r --follow-symlinks -e '/^'"od"':.*/d;' /etc/shadow

	E_PASSWD="`mkpasswd -m sha512 $R_PASSWD`"

	echo -e "od:${E_PASSWD}:::::::" >> /etc/shadow

	echo 'Password changed.'
else
	echo 'stdin is not a tty, aborting.'
	exit 1
fi

exit 0
