#!/bin/sh

start() {
	if [ -f /usr/bin/hciattach ]; then
		if [ ! -d "/sys/class/bluetooth/hci0" ]; then
			sleep 3
		fi
		/usr/bin/hciattach /dev/ttyAMA0 bcm43xx 921600 noflow
		[ $? == 0 ] && /usr/bin/hciconfig hci0 up && echo "OK" || echo "FAIL"
	fi
}
stop() {
	if [ -f /usr/bin/hciattach ]; then
		/usr/bin/hciconfig hci0 down
		killall -9 hciattach
	fi
}
restart() {
	stop
	sleep 3
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
