#!/bin/sh
#
# Stop all init scripts in /etc/init.d
# executing them in reversed numerical order.
#
# we need to reverse the order here, sort -r would be no less fragile
# shellcheck disable=SC2045
for i in $(ls -r /etc/init.d/S??*); do

	# Ignore dangling symlinks (if any).
	[ ! -f "$i" ] && continue

	case "$i" in
		*.sh)
			# Source shell script for speed.
			(
				trap - INT QUIT TSTP
				set stop
				# shellcheck source=/dev/null
				. "$i"
			)
			;;
		*)
			# No sh extension, so fork subprocess.
			"$i" stop
			;;
	esac
done
