#!/bin/sh
#
# Start/stop dhcpcd
#

DAEMON="dhcpcd"
CONFIG="/etc/dhcpcd.conf"
PIDFILE="/var/run/$DAEMON/pid"

[ -f $CONFIG ] || exit 0

case "$1" in
	start)
		echo "Starting dhcpcd..."
		start-stop-daemon -S -x "/sbin/$DAEMON" -p "$PIDFILE" -- -f "$CONFIG"
		;;
	stop)
		echo "Stopping dhcpcd..."
		start-stop-daemon -K -x "/sbin/$DAEMON" -p "$PIDFILE" -o
		;;
	reload|force-reload)
		echo "Reloading dhcpcd configuration..."
		"$DAEMON" -s reload
		;;
	restart)
		"$0" stop
		sleep 1 # Prevent race condition: ensure dhcpcd stops before start.
		"$0" start
		;;
	*)
		echo "Usage: $0 {start|stop|restart|reload|force-reload}"
		exit 1
esac
