ifeq ($(BR2_PACKAGE_USER_INITRD_BASH),y)
define USER_INITRD_BASH_INSTALL
	make bash-reinstall TARGET_DIR=$(OUTPUT_DIR)
endef
endif

ifeq ($(BR2_PACKAGE_USER_INITRD_CRYPTSETUP),y)
define USER_INITRD_CRYPTSETUP_INSTALL
	make cryptsetup-reinstall TARGET_DIR=$(OUTPUT_DIR)
endef
endif

ifeq ($(BR2_PACKAGE_USER_INITRD_BUSYBOX),y)
define USER_INITRD_BUSYBOX_INSTALL
	make busybox-reinstall TARGET_DIR=$(OUTPUT_DIR)
endef
endif

ifeq ($(BR2_PACKAGE_USER_INITRD_COREUTILS),y)
define USER_INITRD_COREUTILS_INSTALL
	make coreutils-reinstall TARGET_DIR=$(OUTPUT_DIR)
endef
endif

ifeq ($(BR2_PACKAGE_USER_INITRD_PROCPS_NG),y)
define USER_INITRD_PROCPS_NG_INSTALL
	make procps-ng-reinstall TARGET_DIR=$(OUTPUT_DIR)
endef
endif

USER_INITRD_BUILD_HOOKS += $(USER_INITRD_BASH_INSTALL)
USER_INITRD_BUILD_HOOKS += $(USER_INITRD_CRYPTSETUP_INSTALL)
USER_INITRD_BUILD_HOOKS += $(USER_INITRD_BUSYBOX_INSTALL)
USER_INITRD_BUILD_HOOKS += $(USER_INITRD_COREUTILS_INSTALL)
USER_INITRD_BUILD_HOOKS += $(USER_INITRD_PROCPS_NG_INSTALL)
