################################################################################
#
# gst1-plugins-dorne
#
################################################################################

GST1_PLUGINS_DORNE_VERSION = 9445faf4fb87ac98e78e88fc0153b60100948570
GST1_PLUGINS_DORNE_SITE = $(call github,Metrological,gst-plugins-dorne,$(GST1_PLUGINS_DORNE_VERSION))
GST1_PLUGINS_DORNE_INSTALL_STAGING = YES
GST1_PLUGINS_DORNE_LICENSE_FILES = COPYING.LIB
GST1_PLUGINS_DORNE_LICENSE = LGPLv2+, LGPLv2.1+


ifeq ($(BR2_PACKAGE_GSTREAMER1_GIT),y)
GST1_PLUGINS_DORNE_AUTORECONF = YES
GST1_PLUGINS_DORNE_AUTORECONF_OPTS = -I $(@D)/common/m4
GST1_PLUGINS_DORNE_GETTEXTIZE = YES
GST1_PLUGINS_DORNE_POST_EXTRACT_HOOKS += GSTREAMER1_COMMON_EXTRACT
GST1_PLUGINS_DORNE_PRE_CONFIGURE_HOOKS += GSTREAMER1_FIX_AUTOPOINT
GST1_PLUGINS_DORNE_POST_INSTALL_TARGET_HOOKS += GSTREAMER1_REMOVE_LA_FILES
endif

GST1_PLUGINS_DORNE_DEPENDENCIES = gstreamer1 gst1-plugins-base

$(eval $(autotools-package))
