################################################################################
#
# gst1-plugins-dorne
#
################################################################################

GST1_PLUGINS_DORNE_VERSION = 609cdcc662ec9bbb55d00f2e118f52ef5dcd7379
GST1_PLUGINS_DORNE_SITE_METHOD = git
GST1_PLUGINS_DORNE_SITE = git@github.com:Metrological/gst-plugins-dorne.git

GST1_PLUGINS_DORNE_INSTALL_STAGING = YES
GST1_PLUGINS_DORNE_LICENSE_FILES = COPYING.LIB
GST1_PLUGINS_DORNE_LICENSE = LGPLv2+, LGPLv2.1+

GST1_PLUGINS_DORNE_AUTORECONF = YES
GST1_PLUGINS_DORNE_AUTORECONF_OPTS = -I $(@D)/common/m4
GST1_PLUGINS_DORNE_GETTEXTIZE = YES

GST1_PLUGINS_DORNE_POST_DOWNLOAD_HOOKS += GSTREAMER1_COMMON_DOWNLOAD
GST1_PLUGINS_DORNE_POST_EXTRACT_HOOKS += GSTREAMER1_COMMON_EXTRACT
GST1_PLUGINS_DORNE_PRE_CONFIGURE_HOOKS += GSTREAMER1_FIX_AUTOPOINT
GST1_PLUGINS_DORNE_POST_INSTALL_TARGET_HOOKS += GSTREAMER1_REMOVE_LA_FILES

GST1_PLUGINS_DORNE_DEPENDENCIES = gluelogic gst1-common gstreamer1 gst1-plugins-base

GST1_PLUGINS_DORNE_CONF_ENV = \
	CFLAGS="$(TARGET_CFLAGS) -Wall -Wextra -Werror -Wno-unused-parameter"


$(eval $(autotools-package))
