#!/bin/sh

start() {
    printf "Starting RBus module: "

    touch /nvram/rbus_support
    start-stop-daemon -S -q -b -m -p /var/run/rtrouted.pid --exec /usr/bin/rtrouted </dev/null >/dev/nul
    [ $? == 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping RBus module: "

    start-stop-daemon -K -q -p /var/run/rtrouted.pid
    [ $? == 0 ] && echo "OK" || echo "FAIL"
    rm -rf /var/run/rtrouted.pid
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
exit $?
