#!/bin/sh

start() {
    printf "Starting RBusCore module: "

    start-stop-daemon -S -b -m -p /var/run/rbus_session_mgr.pid --exec /usr/bin/rbus_session_mgr </dev/null >/dev/nul
    [ $? == 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping RBusCore module: "

    start-stop-daemon -K -q -p /var/run/rbus_session_mgr.pid
    [ $? == 0 ] && echo "OK" || echo "FAIL"
    rm -rf /var/run/rbus_session_mgr.pid
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
exit $?
