################################################################################
#
# wpeframework-avs
#
################################################################################

WPEFRAMEWORK_AVS_VERSION = 5f4f7f5469d814da0cec048ec77335f923153495
WPEFRAMEWORK_AVS_SITE_METHOD = git
WPEFRAMEWORK_AVS_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginAVS.git
WPEFRAMEWORK_AVS_INSTALL_STAGING = YES
WPEFRAMEWORK_AVS_CONF_OPTS += -DBUILD_REFERENCE=$(WPEFRAMEWORK_AVS_VERSION)
WPEFRAMEWORK_AVS_DEPENDECIES += wpeframework avs-device-sdk

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLUGIN_NAME),)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_NAME=$(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLUGIN_NAME)
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUTOSTART),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_AUTOSTART=true
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_AUTOSTART=false
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLATFORM_RPI3),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_PLATFORM="rpi3"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLATFORM_CUSTOM),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_PLATFORM=$(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLATFORM_CUSTOM_VALUE)
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_DATA_PATH),)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_DATA_PATH=$(BR2_PACKAGE_WPEFRAMEWORK_AVS_DATA_PATH)
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_CUSTOM_ALEXA_CLIENT_CONFIG),"")
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ALEXA_CLIENT_CONFIG=$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_CUSTOM_ALEXA_CLIENT_CONFIG))
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ALEXA_CLIENT_CONFIG="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_DATA_PATH))/$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLUGIN_NAME))/AlexaClientSDKConfig.json"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_CUSTOM_SMART_SCREEN_CONFIG),"")
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_SMART_SCREEN_CONFIG=$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_CUSTOM_SMART_SCREEN_CONFIG))
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_SMART_SCREEN_CONFIG="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_DATA_PATH))/$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLUGIN_NAME))/SmartScreenSDKConfig.json"
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_LOG_LEVEL_NONE),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="NONE"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_LOG_LEVEL_CRITICAL),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="CRITICAL"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_LOG_LEVEL_ERROR),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="ERROR"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_LOG_LEVEL_WARN),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="WARN"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_LOG_LEVEL_DEBUG0),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="DEBUG0"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_LOG_LEVEL_DEBUG9),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_LOG_LEVEL="DEBU9"
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUDIOSOURCE_PORTAUDIO),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE="PORTAUDIO"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUDIOSOURCE_BLRC),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE="BluetoothRemoteControl"
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUDIOSOURCE_CUSTOM),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE=$(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUDIOSOURCE_CUSTOM_VALUE)
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUDIOSOURCE),)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_AUDIOSOURCE=$(BR2_PACKAGE_WPEFRAMEWORK_AVS_AUDIOSOURCE)
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_ENABLE_PORTAUDIO_SUPPORT),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_PORTAUDIO_SUPPORT=ON
WPEFRAMEWORK_AVS_DEPENDECIES += portaudio
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_PORTAUDIO_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_ENABLE_SMART_SCREEN_SUPPORT),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN_SUPPORT=ON
WPEFRAMEWORK_AVS_DEPENDECIES += alexa-smart-screen-sdk
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_ENABLE_SMART_SCREEN),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN=true
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN=false
endif
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_SMART_SCREEN_SUPPORT=OFF
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_ENABLE_KWD_SUPPORT),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD_SUPPORT=ON
WPEFRAMEWORK_AVS_DEPENDECIES += alexa-pryon-kwd
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_ENABLE_KWD),y)
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD=true
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD=false
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_AVS_CUSTOM_KWD_MODELS_PATH),"")
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_KWD_MODELS_PATH=$(BR2_PACKAGE_WPEFRAMEWORK_AVS_CUSTOM_KWD_MODELS_PATH)
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_KWD_MODELS_PATH="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_DATA_PATH))/$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_AVS_PLUGIN_NAME))/models"
endif
else
WPEFRAMEWORK_AVS_CONF_OPTS += -DPLUGIN_AVS_ENABLE_KWD_SUPPORT=OFF
endif


$(eval $(cmake-package))
