#!/bin/sh

PERSISTENT=/root

start() {
	#sleep for nxserver to come up
	sleep 2
        /etc/init.d/periodicSync &
}
stop() {
	killall periodicSync
}
restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
