#!/bin/sh
# resize2fs   rootfs partition
#
PATH=/bin:/usr/bin:/sbin:/usr/sbin
start() {
    printf "start resize to   rootfs:\n"
    /usr/sbin/resize2fs /dev/mmcblk0p2
}

stop() {
    printf "stop:\n"
}

restart() {
    stop
    start
}

case   "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart|reload)
        restart
        ;;
*)

    echo "Usage: $0   {start|stop|restart}"
    exit 1
esac

