################################################################################
#
# intelce-performancetools
#
################################################################################
INTELCE_PERFORMANCETOOLS_VERSION = ${INTELCE_SDK_VERSION}
INTELCE_PERFORMANCETOOLS_SITE = ${INTELCE_SDK_DIR}/empty
INTELCE_PERFORMANCETOOLS_SITE_METHOD = local
INTELCE_PERFORMANCETOOLS_LICENSE = PROPRIETARY
INTELCE_PERFORMANCETOOLS_REDISTRIBUTE = NO
INTELCE_PERFORMANCETOOLS_DEPENDENCIES = intelce-sdk
INTELCE_PERFORMANCETOOLS_INSTALL_STAGING = YES

INTELCE_PERFORMANCETOOLS_BUILD_ENV = \
    BUILD_TARGET_DIR=${INTELCE_PERFORMANCETOOLS_DIR} \
    BUILD_SMD_COMMOM=false 
    
define INTELCE_PERFORMANCETOOLS_CONFIGURE_CMDS
   
endef

define INTELCE_PERFORMANCETOOLS_BUILD_CMDS
    if [ -d "${INTELCE_PERFORMANCETOOLS_DIR}/build_i686" ] ; then \
       rm -rf "${INTELCE_PERFORMANCETOOLS_DIR}/build_i686"; \
    fi

    if [ -d "${INTELCE_PERFORMANCETOOLS_DIR}/binaries" ] ; then \
       rm -rf "${INTELCE_PERFORMANCETOOLS_DIR}/binaries" ; \
    fi
    
    if [ -d "${INTELCE_PERFORMANCETOOLS_DIR}/project_build_i686" ] ; then \
       rm -rf "${INTELCE_PERFORMANCETOOLS_DIR}/project_build_i686" ; \
    fi
    
    ${INTELCE_PERFORMANCETOOLS_BUILD_ENV} ${INTELCESDK-BUILD} performancetools
endef

define INTELCE_PERFORMANCETOOLS_INSTALL_STAGING_CMDS
    $(call INTELCE_SDK_INSTALL_TO_STAGING,${INTELCE_PERFORMANCETOOLS_DIR}/build_i686/staging_dir) 
endef

define INTELCE_PERFORMANCETOOLS_INSTALL_TARGET_CMDS
    $(call INTELCE_SDK_INSTALL_TO_TARGET,${INTELCE_PERFORMANCETOOLS_DIR}/project_build_i686/IntelCE/root)
endef

$(eval $(generic-package))
