################################################################################
#
# Plugin Netflix
#
################################################################################
PLUGIN_NETFLIX_VERSION = trunk
PLUGIN_NETFLIX_SITE = git@git.integraal.info:Integraal/plugins
PLUGIN_NETFLIX_SUBDIR = src/netflix
PLUGIN_NETFLIX_SITE_METHOD = git
PLUGIN_NETFLIX_INSTALL_STAGING = NO
PLUGIN_NETFLIX_DEPENDENCIES = bridge bridge-contracts 
PLUGIN_NETFLIX_CONF_OPTS = -DBUILD_REFERENCE=${PLUGIN_NETFLIX_VERSION}

ifeq ($(BR2_PACKAGE_NETFLIX5),y)
# Netflix 5 has a little different API, use "netflix5" branch for now.
PLUGIN_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5=true
PLUGIN_NETFLIX_DEPENDENCIES = netflix5
ifeq ($(BR2_PACKAGE_NETFLIX5_1),y)
PLUGIN_NETFLIX_CONF_OPTS += -DNETFLIX_VERSION_5_1=true
endif
endif

ifeq ($(BR2_PACKAGE_BRIDGE_DEBUG),y)
PLUGIN_NETFLIX_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

# TODO: Do not have WPEFRAMEWORK versioning yet
# PLUGIN_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_VERSION="$(WEBBRIDGE_BUILD_VERSION)-dev"

ifeq ($(BR2_PACKAGE_PLUGIN_NETFLIX_AUTOSTART),y)
PLUGIN_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_AUTOSTART=true
else
PLUGIN_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_AUTOSTART=false
endif

ifneq ($(BR2_PACKAGE_PLUGIN_NETFLIX_MODEL),)
PLUGIN_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_MODEL="$(call qstrip,$(BR2_PACKAGE_PLUGIN_NETFLIX_MODEL))"
endif

ifneq ($(BR2_PACKAGE_PLUGIN_NETFLIX_SUSPEND_TIMEOUT),)
PLUGIN_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_SUSPENDTIMEOUT="$(call qstrip,$(BR2_PACKAGE_PLUGIN_NETFLIX_SUSPEND_TIMEOUT))"
endif

ifneq ($(BR2_PACKAGE_PLUGIN_NETFLIX_RESUME_TIMEOUT),)
PLUGIN_NETFLIX_CONF_OPTS += -DPLUGIN_NETFLIX_RESUMETIMEOUT="$(call qstrip,$(BR2_PACKAGE_PLUGIN_NETFLIX_RESUME_TIMEOUT))"
endif

$(eval $(cmake-package))

