#!/bin/sh

case "$IFACE" in
	wlan[0-9])
		;;
	*)
		exit 0
		;;
esac

if [ -z "$CONF_FILE" ] ; then
	CONF_FILE=/etc/local/network/config-${IFACE}.conf
fi

[ -f $CONF_FILE ] || exit 1
. $CONF_FILE

case "$WLAN_ENCRYPTION" in
	wep)
		if [ "${WLAN_PASSPHRASE:0:2}" = "s:" ] ; then
			WLAN_PASSPHRASE="\"${WLAN_PASSPHRASE:2}\""
		fi
		echo "network={
			ssid=\"$WLAN_ESSID\"
			scan_ssid=1
			priority=5
			key_mgmt=NONE
			wep_key0=$WLAN_PASSPHRASE
			wep_tx_keyidx=0
		}" > /tmp/.${IFACE}_config
		;;

	wpa|wpa2)
		/usr/sbin/wpa_passphrase \
			"$WLAN_ESSID" "$WLAN_PASSPHRASE" > /tmp/.${IFACE}_config
		;;

	none)
		;;

	*)
		exit 1
esac

ip link set ${IFACE} up
[ $? -ne 0 ] && exit 1

iw ${IFACE} disconnect
[ $? -ne 0 ] && exit 1

iw ${IFACE} set type managed
[ $? -ne 0 ] && exit 1

if [ -f "/var/run/wpa_supplicant_${IFACE}.pid" ] ; then
	/sbin/start-stop-daemon -K -q -p /var/run/wpa_supplicant_${IFACE}.pid
fi

if [ "$WLAN_ENCRYPTION" = "none" ] ; then
	iw ${IFACE} connect ${WLAN_ESSID}
else
	/usr/sbin/wpa_supplicant -B -D nl80211,wext -i "$IFACE" \
		-c /tmp/.${IFACE}_config -P /var/run/wpa_supplicant_${IFACE}.pid
fi

exit $?
