#!/bin/sh

cleanup() {
	/usr/sbin/start-stop-daemon -K -q -o -p /var/run/udhcpc_${IFACE}.pid
	rm -f /var/run/udhcpc_${IFACE}.pid

	/sbin/start-stop-daemon -K -q -o -p /var/run/wpa_supplicant_${IFACE}.pid
	rm -f /var/run/wpa_supplicant_${IFACE}.pid

	iw ${IFACE} disconnect

	ip -4 addr flush dev ${IFACE}

	ip link set ${IFACE} down

	exit $1
}

case "$IFACE" in
	wlan[0-9])
		;;
	*)
		exit 0
		;;
esac

if [ -z "$CONF_FILE" ] ; then
	CONF_FILE=/etc/local/network/config-${IFACE}.conf
fi

[ -f $CONF_FILE ] || exit 1
. $CONF_FILE

case "$WLAN_ENCRYPTION" in
	wep)
		if [ "${WLAN_PASSPHRASE:0:2}" = "s:" ] ; then
			WLAN_PASSPHRASE="\"${WLAN_PASSPHRASE:2}\""
		fi
		echo "network={
			ssid=\"$WLAN_ESSID\"
			scan_ssid=1
			priority=5
			key_mgmt=NONE
			wep_key0=$WLAN_PASSPHRASE
			wep_tx_keyidx=0
		}" > /tmp/.${IFACE}_config
		;;

	wpa|wpa2)
		/usr/sbin/wpa_passphrase \
			"$WLAN_ESSID" "$WLAN_PASSPHRASE" > /tmp/.${IFACE}_config
		;;

	none)
		;;

	*)
		echo "Invalid encryption type: \"$WLAN_ENCRYPTION\""
		cleanup 1
esac

ip link set ${IFACE} up
ERR=$?
[ $ERR -ne 0 ] && cleanup $ERR

iw ${IFACE} set type managed 2>/dev/null

if [ "$WLAN_ENCRYPTION" = "none" ] ; then
	iw ${IFACE} connect ${WLAN_ESSID}
else
	/usr/sbin/wpa_supplicant -B -D nl80211,wext -i "$IFACE" \
		-c /tmp/.${IFACE}_config -P /var/run/wpa_supplicant_${IFACE}.pid
fi

ERR=$?
[ $ERR -ne 0 ] && cleanup $ERR

WLAN_DHCP_RETRIES=10
PIDFILE=/var/run/udhcpc_${IFACE}.pid

/sbin/udhcpc -i "$IFACE" -n -R -S -t "$WLAN_DHCP_RETRIES" -p "$PIDFILE"
ERR=$?
[ $ERR -ne 0 ] && cleanup $ERR

exit 0
