################################################################################
#
# wpeframework-rdkservices
#
################################################################################

WPEFRAMEWORK_RDKSERVICES_VERSION = fafde8d9fb3aeca340d6a823d9d6de6f5c60d996
WPEFRAMEWORK_RDKSERVICES_SITE = $(call github,rdkcentral,rdkservices,$(WPEFRAMEWORK_RDKSERVICES_VERSION))
WPEFRAMEWORK_RDKSERVICES_INSTALL_STAGING = YES
WPEFRAMEWORK_RDKSERVICES_DEPENDENCIES = wpeframework

WPEFRAMEWORK_RDKSERVICES_OPKG_NAME = "wpeframework-rdkservices"
WPEFRAMEWORK_RDKSERVICES_OPKG_VERSION = "1.0.0"
WPEFRAMEWORK_RDKSERVICES_OPKG_ARCHITECTURE = "${BR2_ARCH}"
WPEFRAMEWORK_RDKSERVICES_OPKG_MAINTAINER = "Metrological"
WPEFRAMEWORK_RDKSERVICES_OPKG_DESCRIPTION = "WPEFramework rdkservices"

WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_RDKSERVICES_VERSION}

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_DEBUG),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=Debug
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_DEBUG_OPTIMIZED),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=DebugOptimized
else ifeq ($( BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_RELEASE_WITH_SYMBOLS),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=ReleaseSymbols
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_RELEASE),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=Release
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_PRODUCTION),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=Production
endif

WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_DISPLAYSETTINGS=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_LOGGING_PREFERENCES=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_USER_PREFERENCES=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_SYSTEMSERVICES=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_CONTROLSERVICE=OFF

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DEVICEINFO),y)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DENABLE_DEVICE_INFO=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR),y)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DENABLE_MONITOR=ON
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_WEBKIT),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_WEBKITBROWSER=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_WEBKITBROWSER_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_WEBKIT}
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_YOUTUBE),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_WEBKITBROWSER_YOUTUBE=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_YOUTUBE_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_YOUTUBE}
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_COBALT),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_COBALT=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_COBALT_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_COBALT}
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_AMAZON),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_AMAZON_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_AMAZON}
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_APPS),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_WEBKITBROWSER_APPS=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_APPS_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_APPS}
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_UX),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_WEBKITBROWSER_UX=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_UX_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_UX}
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_MONITOR_NETFLIX),)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_NETFLIX=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_NETFLIX_MEMORYLIMIT=${BR2_PACKAGE_WPEFRAMEWORK_MONITOR_NETFLIX}
endif
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_TRACECONTROL),y)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DENABLE_TRACE_CONTROL=ON
endif


ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_LOCATIONSYNC),y)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DENABLE_LOCATION_SYNC=ON
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_LOCATIONSYNC_URI=${BR2_PACKAGE_WPEFRAMEWORK_LOCATIONSYNC_URI}
endif

$(eval $(cmake-package))
