################################################################################
#
# wpeframework-rdkservices
#
################################################################################

WPEFRAMEWORK_RDKSERVICES_VERSION = fafde8d9fb3aeca340d6a823d9d6de6f5c60d996
WPEFRAMEWORK_RDKSERVICES_SITE = $(call github,rdkcentral,rdkservices,$(WPEFRAMEWORK_RDKSERVICES_VERSION))
WPEFRAMEWORK_RDKSERVICES_INSTALL_STAGING = YES
WPEFRAMEWORK_RDKSERVICES_DEPENDENCIES = wpeframework

WPEFRAMEWORK_RDKSERVICES_OPKG_NAME = "wpeframework-rdkservices"
WPEFRAMEWORK_RDKSERVICES_OPKG_VERSION = "1.0.0"
WPEFRAMEWORK_RDKSERVICES_OPKG_ARCHITECTURE = "${BR2_ARCH}"
WPEFRAMEWORK_RDKSERVICES_OPKG_MAINTAINER = "Metrological"
WPEFRAMEWORK_RDKSERVICES_OPKG_DESCRIPTION = "WPEFramework rdkservices"

WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_RDKSERVICES_VERSION}

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_DEBUG),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=Debug
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_DEBUG_OPTIMIZED),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=DebugOptimized
else ifeq ($( BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_RELEASE_WITH_SYMBOLS),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=ReleaseSymbols
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_RELEASE),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=Release
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_BUILD_TYPE_PRODUCTION),y)
        WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DBUILD_TYPE=Production
endif

WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_DISPLAYSETTINGS=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_LOGGING_PREFERENCES=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_USER_PREFERENCES=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_SYSTEMSERVICES=OFF
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DPLUGIN_CONTROLSERVICE=OFF

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_RDKSERVICES_DEVICEINFO),y)
WPEFRAMEWORK_RDKSERVICES_CONF_OPTS += -DENABLE_DEVICE_INFO=ON
endif

$(eval $(cmake-package))
