# Contains settings that are important for the raspberry pi 0 to work with Open.HD
CONFIG_AIO=y
CONFIG_ADVISE_SYSCALLS=y

CONFIG_SECCOMP_FILTER=y

CONFIG_ARCH_MMAP_RND_BITS_MAX=16

CONFIG_BLK_DEV_BSGLIB=y

# CONFIG_IOSCHED_CFQ is not set

CONFIG_VMSPLIT_3G=y
# CONFIG_VMSPLIT_3G_OPT is not set
# CONFIG_VMSPLIT_2G is not set
# CONFIG_VMSPLIT_1G is not set
CONFIG_PAGE_OFFSET=0xC0000000

CONFIG_SECCOMP=y

CONFIG_NET_CORE=y

CONFIG_MDIO_BITBANG=m

CONFIG_RTL8812AU=m

CONFIG_SERIO=m
CONFIG_SERIO_SERPORT=m
# CONFIG_SERIO_AMBAKMI is not set
# CONFIG_SERIO_LIBPS2 is not set
CONFIG_SERIO_RAW=m
# CONFIG_SERIO_ALTERA_PS2 is not set
# CONFIG_SERIO_PS2MULT is not set
# CONFIG_SERIO_ARC_PS2 is not set
# CONFIG_SERIO_APBPS2 is not set

CONFIG_THERMAL_BCM2835=y

#
# Webcam, TV (analog/digital) USB devices
#
CONFIG_VIDEO_EM28XX=m
CONFIG_VIDEO_EM28XX_V4L2=m
# CONFIG_VIDEO_EM28XX_ALSA is not set
CONFIG_V4L_PLATFORM_DRIVERS=y
CONFIG_VIDEO_BCM2835=y
CONFIG_VIDEO_BCM2835_MMAL=m
CONFIG_SOC_CAMERA=m
# CONFIG_SOC_CAMERA_PLATFORM is not set
# CONFIG_VIDEO_XILINX is not set
# CONFIG_V4L_MEM2MEM_DRIVERS is not set
# CONFIG_V4L_TEST_DRIVERS is not set

CONFIG_USB_MON=m

