WPEFRAMEWORK_SWITCHBOARD_VERSION = ea0be82472b15203679f0eea00ace6e47716e8b1
WPEFRAMEWORK_SWITCHBOARD_SITE_METHOD = git
WPEFRAMEWORK_SWITCHBOARD_SITE = git@github.com:Metrological/webbridge.git
WPEFRAMEWORK_SWITCHBOARD_INSTALL_STAGING = YES
WPEFRAMEWORK_SWITCHBOARD_DEPENDENCIES = WPEFramework

WPEFRAMEWORK_SWITCHBOARD_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_SWITCHBOARD_VERSION}

$(eval $(cmake-package))

