################################################################################
#
# Plugins Domotica
#
################################################################################
PLUGIN_DOMOTICA_VERSION = trunk
PLUGIN_DOMOTICA_SITE = git@git.integraal.info:Integraal/modules
PLUGIN_DOMOTICA_SUBDIR = src
PLUGIN_DOMOTICA_SITE_METHOD = git
PLUGIN_DOMOTICA_INSTALL_STAGING = NO
PLUGIN_DOMOTICA_DEPENDENCIES = bridge bridge-contracts
PLUGIN_DOMOTICA_CONF_OPTS += -DBUILD_REFERENCE=${PLUGIN_DOMOTICA_VERSION}

ifeq ($(BR2_PACKAGE_BRIDGE_DEBUG),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
endif

ifeq ($(BR2_PACKAGE_PLUGIN_BARN),y) 
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_BARN=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_BUTLER),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_BUTLER=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_I2CCONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_I2CCONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_IOCONTROL),y)
# PLUGIN_DOMOTICA_CONF_OPTS += -DRASPBERRYPI=ON
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL=ON
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN1_ID=27
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN1_MODE="Both"
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN1_STATE=true
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN1_PULL=true
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN2_ID=17
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN2_MODE="Output"
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN2_STATE=false
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN3_ID=12
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN3_MODE="Output"
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN3_STATE=false
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN4_ID=18
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN4_MODE="Output"
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_IOCONTROL_PIN4_STATE=false
endif

ifeq ($(BR2_PACKAGE_PLUGIN_ONEWIRECONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_ONEWIRECONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_RADIOCONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_RADIOCONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_SCRIPTENGINE),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_SCRIPTENGINE=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_SPICONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_SPICONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_TEMPCONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_TEMPCONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_VIRTUALCONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_VIRTUALCONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_ZIGBEECONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_ZIGBEECONTROL=ON
endif

ifeq ($(BR2_PACKAGE_PLUGIN_ZWAVECONTROL),y)
PLUGIN_DOMOTICA_CONF_OPTS += -DPLUGIN_ZWAVECONTROL=ON
endif

$(eval $(cmake-package))
