#!/bin/sh

# shellcheck disable=SC2276
global.bootm.oftree="/boot/socfpga_cyclone5_de0_nano_soc.dtb"
global.bootm.image="/boot/zImage"

#bootargs-ip

global.linux.bootargs.dyn.root="root=/dev/mmcblk0p3 rw rootwait"
