#!/bin/sh

[ "${IFACE:0:4}" = "wlan" ] || exit 0

USB_ONLINE=`cat '/sys/class/power_supply/usb-charger/online'`
DC_ONLINE=`cat '/sys/class/power_supply/usb-charger/online'`
BATTERY_LEVEL=`cat '/sys/class/power_supply/jz-battery/voltage_now'`
BATTERY_MIN=`cat '/sys/class/power_supply/jz-battery/voltage_min_design'`
BATTERY_MAX=`cat '/sys/class/power_supply/jz-battery/voltage_max_design'`

BATTERY_LEVEL=$(expr $(expr $BATTERY_LEVEL - $BATTERY_MIN) \* 100 / $(expr $BATTERY_MAX - $BATTERY_MIN))

# If the battery level is low, the battery level monitor may have
# already changed how the LED blinks, so we don't override that
[ "$USB_ONLINE" -eq 0 \
	-a "$DC_ONLINE" -eq 0 \
	-a "$BATTERY_LEVEL" -lt 10 ] && exit 0

HAS_OTHER_INTERFACES=no
for i in `ls /sys/class/net` ; do
	[ "${i:0:4}" = "wlan" ] || continue
	[ "$i" != "$IFACE" ] || continue

	if [ `cat /sys/class/net/$i/operstate` = "up" ] ; then
		HAS_OTHER_INTERFACES=yes
		break
	fi
done

# Stop blinking only if no other wlan interface is up
if [ "$HAS_OTHER_INTERFACES" != "yes" ] ; then
	echo 'none' > /sys/class/leds/led/trigger
	cat /sys/class/leds/led/max_brightness > /sys/class/leds/led/brightness
fi
