#!/bin/sh

# Only blink the LED when a wlan interface is enabled
[ ${IFACE:0:4} = "wlan" ] || exit 0

USB_ONLINE=`cat '/sys/class/power_supply/usb-charger/online'`
DC_ONLINE=`cat '/sys/class/power_supply/dc-charger/online'`
BATTERY_LEVEL=`cat '/sys/class/power_supply/jz-battery/voltage_now'`
BATTERY_MIN=`cat '/sys/class/power_supply/jz-battery/voltage_min_design'`
BATTERY_MAX=`cat '/sys/class/power_supply/jz-battery/voltage_max_design'`

BATTERY_LEVEL=$(expr $(expr $BATTERY_LEVEL - $BATTERY_MIN) \* 100 / $(expr $BATTERY_MAX - $BATTERY_MIN))

# Don't change the blinking mode if the battery level is
# low, so that the low battery level warning will work
[ "$USB_ONLINE" -eq 0 \
	-a "$DC_ONLINE" -eq 0 \
	-a "$BATTERY_LEVEL" -lt 10 ] && exit 0

echo 'timer' > /sys/class/leds/led/trigger
echo '100' > /sys/class/leds/led/delay_on
echo '1400' > /sys/class/leds/led/delay_off
