#!/bin/sh

start() {
        printf "Starting opencdmi service: "
        umask 077
        start-stop-daemon -S -q -p /var/run/opencdmi.pid --exec /usr/bin/cdmiservice > /dev/null 2>&1
        [ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
        printf "Stopping opencdmi service: "
        start-stop-daemon -K -q -p /var/run/opencdmi.pid
        [ $? == 0 ] && echo "OK" || echo "FAIL"
        rm -rf /var/run/opencdmi.pid
}
restart() {
        stop
        start
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  restart|reload)
        restart
        ;;
  *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit $?


