#!/bin/sh

start() {
    printf "Starting WebPA CcspCR module: "

    ln -sf /usr/ccsp/ccsp_msg.cfg /tmp/ccsp_msg.cfg
    rm -rf /tmp/syscfg.shmid
    syscfg_create -f /usr/ccsp/syscfg.db
    start-stop-daemon -S -q -b --exec /usr/bin/CcspCrSsp -- -subsys eRT. </dev/null >/dev/nul
    [ $? == 0 ] && echo "OK" || echo "FAIL"
}

stop() {
    printf "Stopping WebPA CcspCR module: "
    start-stop-daemon -K -q --exec /usr/bin/CcspCrSsp
    [ $? == 0 ] && echo "OK" || echo "FAIL"
}

restart() {
	stop
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac
exit $?
