#!/bin/sh
DAEMON="mender-connect"
DAEMON_PATH="/usr/bin/mender-connect"
PIDFILE="/var/run/${DAEMON}.pid"

MENDER_CONNECT_ARGS=""

# shellcheck source=/dev/null
[ -r "/etc/default/$DAEMON" ] && . "/etc/default/$DAEMON"

start() {
	printf 'Starting %s: ' "${DAEMON}"
	umask 077
	# shellcheck disable=SC2086 # we need the word splitting
	start-stop-daemon -bmSqp "$PIDFILE" -x ${DAEMON_PATH} \
		-- -daemon ${DAEMON_ARGS}
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "${DAEMON}"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		# Restart, since there is no true "reload" feature.
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
esac
