################################################################################
#
# pxcore
#
################################################################################
PXCORE_VERSION = 0db82d484abadebadeb3d8253b5a55924bcebaf8
PXCORE_SITE_METHOD = git
PXCORE_SITE = git://github.com/pxscene/pxCore
PXCORE_INSTALL_STAGING = YES
PXCORE_AUTORECONF = YES
PXCORE_AUTORECONF_OPTS = "-Icfg"

PXCORE_DEPENDENCIES = openssl freetype westeros util-linux libpng libcurl rtremote pxcore-libnode

PXCORE_CONF_OPTS += \
    -DBUILD_WITH_WAYLAND=ON \
    -DBUILD_WITH_WESTEROS=ON \
    -DBUILD_WITH_TEXTURE_USAGE_MONITORING=ON \
    -DPXCORE_COMPILE_WARNINGS_AS_ERRORS=OFF \
    -DPXSCENE_COMPILE_WARNINGS_AS_ERRORS=OFF \
    -DCMAKE_SKIP_RPATH=ON \
    -DPXCORE_WAYLAND_EGL=ON \
    -DBUILD_PXSCENE_WAYLAND_EGL=ON \
    -DPXCORE_MATRIX_HELPERS=OFF \
    -DBUILD_PXWAYLAND_SHARED_LIB=OFF \
    -DBUILD_PXWAYLAND_STATIC_LIB=OFF \
    -DBUILD_PXSCENE_APP_WITH_PXSCENE_LIB=ON \
    -DPXCORE_ESSOS=ON \
    -DBUILD_PXSCENE_ESSOS=ON \
    -DPREFER_SYSTEM_LIBRARIES=ON \
    -DDISABLE_TURBO_JPEG=ON \
    -DDISABLE_DEBUG_MODE=ON \
    -DBUILD_OPTIMUS_STATIC_LIB=ON \
    -DSPARK_BACKGROUND_TEXTURE_CREATION=ON \
    -DSPARK_ENABLE_LRU_TEXTURE_EJECTION=OFF \
    -DHOSTNAME=raspberrypi \
    -DDISABLE_WAYLAND="TRUE"


PXCORE_PRE_CONFIGURE_HOOKS += BUILD_DEPENDENCY_LIBNODE
$(eval $(cmake-package))
