#!/bin/sh

DAEMON="pb-discover"
PIDFILE="/var/run/$DAEMON.pid"

# shellcheck source=/dev/null
[ -r "/etc/default/petitboot" ] && . "/etc/default/petitboot"

if [ "$(pb-config debug)" = "enabled" ] ; then
	PB_DISCOVER_ARGS="$PB_DISCOVER_ARGS --verbose"
fi

start() {
	printf 'Starting %s: ' "$DAEMON"
	# shellcheck disable=SC2174 # only apply -m to deepest dir
	mkdir -p -m 0775 /var/log/petitboot
	chown petituser:petitgroup /var/log/petitboot

	# shellcheck disable=SC2086 # we need the word splitting
	start-stop-daemon -S -q -b -m -p "$PIDFILE" -x "/usr/sbin/$DAEMON" \
		-- $PB_DISCOVER_ARGS
	status=$?
	if [ "$status" -eq 0 ]; then
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

stop() {
	printf 'Stopping %s: ' "$DAEMON"
	start-stop-daemon -K -q -p "$PIDFILE"
	status=$?
	if [ "$status" -eq 0 ]; then
		rm -f "$PIDFILE"
		echo "OK"
	else
		echo "FAIL"
	fi
	return "$status"
}

restart() {
	stop
	sleep 1
	start
}

case "$1" in
	start|stop|restart)
		"$1";;
	reload)
		restart;;
	*)
		echo "Usage: $0 {start|stop|restart|reload}"
		exit 1
		;;
esac
