################################################################################
#
# virglrenderer
#
################################################################################

VIRGLRENDERER_VERSION = 1.3.0
VIRGLRENDERER_SITE = https://gitlab.freedesktop.org/virgl/virglrenderer/-/archive/$(VIRGLRENDERER_VERSION)
VIRGLRENDERER_LICENSE = MIT
VIRGLRENDERER_LICENSE_FILES = COPYING
VIRGLRENDERER_INSTALL_STAGING = YES
VIRGLRENDERER_DEPENDENCIES = \
	libepoxy \
	host-pkgconf \
	host-python3 \
	host-python-pyyaml
VIRGLRENDERER_CPE_ID_VALID = YES

ifeq ($(BR2_PACKAGE_VIRGLRENDERER_VIRGL),y)
ifeq ($(BR2_PACKAGE_HAS_LIBEGL)$(BR2_PACKAGE_HAS_LIBGBM),yy)
VIRGLRENDERER_PLATFORMS += egl
VIRGLRENDERER_DEPENDENCIES += \
	libegl \
	libgbm
endif

ifeq ($(BR2_PACKAGE_HAS_LIBGL),y)
VIRGLRENDERER_PLATFORMS += glx
VIRGLRENDERER_DEPENDENCIES += libgl
endif
endif # BR2_PACKAGE_VIRGLRENDERER_VIRGL

VIRGLRENDERER_CONF_OPTS += -Dplatforms=$(subst $(space),$(comma),$(VIRGLRENDERER_PLATFORMS))

ifeq ($(BR2_PACKAGE_VIRGLRENDERER_VENUS),y)
VIRGLRENDERER_CONF_OPTS += -Dvenus=true
VIRGLRENDERER_DEPENDENCIES += \
	vulkan-headers \
	vulkan-loader
else
VIRGLRENDERER_CONF_OPTS += -Dvenus=false
endif

VIRGLRENDERER_DRM_BACKENDS-$(BR2_PACKAGE_VIRGLRENDERER_DRM_BACKEND_AMDGPU) += amdgpu-experimental
VIRGLRENDERER_DRM_BACKENDS-$(BR2_PACKAGE_VIRGLRENDERER_DRM_BACKEND_INTEL) += i915-experimental
VIRGLRENDERER_DRM_BACKENDS-$(BR2_PACKAGE_VIRGLRENDERER_DRM_BACKEND_MSM) += msm
VIRGLRENDERER_DRM_BACKENDS-$(BR2_PACKAGE_VIRGLRENDERER_DRM_BACKEND_PANFROST) += panfrost-experimental

VIRGLRENDERER_CONF_OPTS += -Ddrm-renderers=$(subst $(space),$(comma),$(VIRGLRENDERER_DRM_BACKENDS-y))

ifneq ($(VIRGLRENDERER_DRM_BACKENDS-y),)
VIRGLRENDERER_DEPENDENCIES += libdrm
endif

ifeq ($(BR2_PACKAGE_VIRGLRENDERER_VAAPI),y)
VIRGLRENDERER_CONF_OPTS += -Dvideo=true
VIRGLRENDERER_DEPENDENCIES += libva libdrm
else
VIRGLRENDERER_CONF_OPTS += -Dvideo=false
endif

$(eval $(meson-package))
