################################################################################
#
# WPEFramework Common plugins
#
################################################################################

WPEFRAMEWORK_COMMON_VERSION = 57dd986476e491112f11bb53caee49bbda97425f
WPEFRAMEWORK_COMMON_SITE_METHOD = git
WPEFRAMEWORK_COMMON_SITE = git@github.com:WebPlatformForEmbedded/WPEFrameworkPlugins.git
WPEFRAMEWORK_COMMON_INSTALL_STAGING = YES
WPEFRAMEWORK_COMMON_DEPENDENCIES = WPEFramework libpng

WPEFRAMEWORK_COMMON_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_COMMON_VERSION}

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DEBUG),y)
# TODO: This recently stopped working, for now pass debug flags explicitly.
#WPEFRAMEWORK_COMMON_CONF_OPTS += -DCMAKE_BUILD_TYPE=Debug
WPEFRAMEWORK_COMMON_CONF_OPTS += -DCMAKE_CXX_FLAGS='-g -Og'
endif

ifeq ($(BR2_PACKAGE_BCM_REFSW),y)
WPEFRAMEWORK_COMMON_DEPENDENCIES = bcm-refsw
endif

# libprovision

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_COMMANDER),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_COMMANDER=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_DEVICEINFO),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_DEVICEINFO=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_LOCATIONSYNC),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_LOCATIONSYNC=ON
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_LOCATIONSYNC_URI=${BR2_PACKAGE_WPEFRAMEWORK_COMMON_LOCATIONSYNC_URI}
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_MONITOR),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_MONITOR=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_REMOTECONTROL),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_REMOTECONTROL=ON
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_REMOTECONTROL_PLUGIN_IRNEXUS),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_REMOTECONTROL_IRNEXUS=ON
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_REMOTECONTROL_PLUGIN_IRNEXUS_MODE),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_REMOTECONTROL_IRMODE="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_REMOTECONTROL_PLUGIN_IRNEXUS_MODE))"
endif
endif
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_SNAPSHOT),y)
WPEFRAMEWORK_COMMON_DEPENDENCIES += libpng
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_SNAPSHOT=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_TIMESYNC),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_TIMESYNC=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_TRACECONTROL),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_TRACECONTROL=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER),y)
WPEFRAMEWORK_COMMON_DEPENDENCIES += wpewebkit
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER=ON
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_AUTOSTART),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_AUTOSTART=true
else
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_AUTOSTART=false
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_STARTURL),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_STARTURL=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_WEBKITBROWSER_STARTURL)
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_USERAGENT),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_USERAGENT=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_WEBKITBROWSER_USERAGENT)
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_MEMORYPROFILE),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_MEMORYPROFILE=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_WEBKITBROWSER_MEMORYPROFILE)
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_MEMORYPRESSURE),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_MEMORYPRESSURE=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_WEBKITBROWSER_MEMORYPRESSURE)
endif
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_MEDIADISKCACHE),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_MEDIADISKCACHE=true
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_DISKCACHE),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_DISKCACHE=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_WEBKITBROWSER_DISKCACHE)
endif
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_XHRCACHE),)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_XHRCACHE=false
endif
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBKITBROWSER_TRANSPARENT),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_TRANSPARENT=true
else
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_TRANSPARENT=false
endif
ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_YOUTUBE),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBKITBROWSER_YOUTUBE=ON
endif
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBPROXY),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBPROXY=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBSERVER),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBSERVER=ON
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COMMON_WEBSHELL),y)
WPEFRAMEWORK_COMMON_CONF_OPTS += -DOPEN_PLUGIN_WEBSHELL=ON
endif

$(eval $(cmake-package))
