#! /bin/sh
### BEGIN INIT INFO
# Provides:          memcached
# Required-Start:    $syslog
# Required-Stop:     $syslog
# Should-Start:        $local_fs
# Should-Stop:        $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description:    memcached - Memory caching daemon
# Description:        memcached - Memory caching daemon
### END INIT INFO

# Usage:
# cp /etc/memcached.conf /etc/memcached_server1.conf
# cp /etc/memcached.conf /etc/memcached_server2.conf
# start all instances:
# /etc/init.d/memcached start
# start one instance:
# /etc/init.d/memcached start server1
# stop all instances:
# /etc/init.d/memcached stop
# stop one instance:
# /etc/init.d/memcached stop server1
# There is no "status" command.

set -e

#DAEMON=/usr/bin/memcached
#DAEMONNAME=memcached
DAEMON=/usr/bin/start-memcached
DAEMON_OPTS="/etc/memcached.conf"


start() {
  echo -n "Starting daemon: "$NAME
  start-stop-daemon --start --quiet --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON -- $DAEMON_OPTS
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}


stop() {
  echo -n "Stopping daemon: "$NAME
  start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
  [ $? = 0 ] && echo "OK" || echo "FAIL"
}


case "$1" in
    start)
  start
  ;;
    stop)
  stop
  ;;
    restart|reload)
  stop
  start
  ;;
  *)
  echo "Usage: $0 {start|stop|restart}"
  exit 1
esac


exit $?
