#!/usr/bin/env bash

set -e
set -o pipefail

. "${0%/*}/helpers"

while getopts "n:o:" OPT; do
    case "${OPT}" in
    o)  output="${OPTARG}";;
    n)  base_name="${OPTARG}";;
    :)  error "option '%s' expects a mandatory argument\n" "${OPTARG}";;
    \?) error "unknown option '%s'\n" "${OPTARG}";;
    esac
done

# Already vendored tarball, nothing to do
if tar tf "${output}" | grep -q "^[^/]*/VENDOR" ; then
    exit 0
fi

post_process_unpack "${base_name}" "${output}"

# Do the Cargo vendoring
pushd "${base_name}" > /dev/null

# Create the local .cargo/config with vendor info
mkdir -p .cargo/
mkdir -p "${CARGO_HOME}"
flock "${CARGO_HOME}"/.br-lock \
cargo vendor \
    --manifest-path ${BR_CARGO_MANIFEST_PATH-Cargo.toml} \
    --locked VENDOR \
    | tee .cargo/config

popd > /dev/null

post_process_repack "$(pwd)" "${base_name}" "${output}"
