################################################################################
#
# qt6positioning
#
################################################################################

QT6POSITIONING_VERSION = $(QT6_VERSION)
QT6POSITIONING_SITE = $(QT6_SITE)
QT6POSITIONING_SOURCE = qtpositioning-$(QT6_SOURCE_TARBALL_PREFIX)-$(QT6POSITIONING_VERSION).tar.xz
QT6POSITIONING_INSTALL_STAGING = YES
QT6POSITIONING_SUPPORTS_IN_SOURCE_BUILD = NO
QT6POSITIONING_CMAKE_BACKEND = ninja

QT6POSITIONING_LICENSE = GPL-2.0 or GPL-3.0 or LGPL-3.0

QT6POSITIONING_LICENSE_FILES = \
	LICENSES/GPL-2.0-only.txt \
	LICENSES/GPL-3.0-only.txt \
	LICENSES/LGPL-3.0-only.txt

QT6POSITIONING_DEPENDENCIES = qt6base

ifeq ($(BR2_PACKAGE_QT6DECLARATIVE)$(BR2_PACKAGE_QT6DECLARATIVE_QUICK),yy)
QT6POSITIONING_DEPENDENCIES += qt6declarative
endif

ifeq ($(BR2_PACKAGE_QT6SERIALPORT),y)
QT6POSITIONING_DEPENDENCIES += qt6serialport
endif

$(eval $(cmake-package))
