################################################################################
#
# wpewebkit-devel
#
################################################################################

WPEWEBKIT_DEVEL_VERSION = 27c1684c70e30debf397ec1e470127b0443019d6
WPEWEBKIT_DEVEL_SITE = $(call github,WebPlatformForEmbedded,WPEWebKit,$(WPEWEBKIT_DEVEL_VERSION))
WPEWEBKIT_DEVEL_INSTALL_STAGING = YES
WPEWEBKIT_DEVEL_LICENSE = LGPL-2.1+, BSD-2-Clause
WPEWEBKIT_DEVEL_LICENSE_FILES = \
	Source/WebCore/LICENSE-APPLE \
	Source/WebCore/LICENSE-LGPL-2.1
WPEWEBKIT_DEVEL_DEPENDENCIES = host-gperf host-python host-ruby \
	harfbuzz cairo icu jpeg libepoxy libgcrypt libgles libsoup libtasn1 \
	libpng libxslt openjpeg webp wpebackend

WPEWEBKIT_DEVEL_CONF_OPTS = \
	-DPORT=WPE \
	-DENABLE_ACCESSIBILITY=OFF \
	-DENABLE_API_TESTS=OFF \
	-DENABLE_MINIBROWSER=OFF \
	-DSILENCE_CROSS_COMPILATION_NOTICES=ON

ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_DEBUG)$(BR2_PACKAGE_WPEWEBKIT_DEVEL_SYMBOLS),y)
WPEWEBKIT_DEVEL_SYMBOL_FLAGS = -g
endif

WPEWEBKIT_DEVEL_BUILD_TYPE = Release
WPEWEBKIT_DEVEL_CXXFLAGS = -O2 -DNDEBUG
ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_DEBUG),y)
WPEWEBKIT_DEVEL_BUILD_TYPE = Debug
WPEWEBKIT_DEVEL_FLAGS += -DCMAKE_BUILD_TYPE=Debug
WPEWEBKIT_DEVEL_CXXFLAGS = -O0
endif

WEBKIT_COMPILER_FLAGS=$(WPEWEBKIT_DEVEL_SYMBOL_FLAGS) $(WPEWEBKIT_DEVEL_CXXFLAGS) -Wno-cast-align
WPEWEBKIT_DEVEL_EXTRA_FLAGS += \
	-DCMAKE_C_FLAGS_RELEASE="$(WEBKIT_COMPILER_FLAGS)" \
	-DCMAKE_CXX_FLAGS_RELEASE="$(WEBKIT_COMPILER_FLAGS)" \
	-DCMAKE_C_FLAGS_DEBUG="$(WEBKIT_COMPILER_FLAGS)" \
	-DCMAKE_CXX_FLAGS_DEBUG="$(WEBKIT_COMPILER_FLAGS)"

WPEWEBKIT_DEVEL_CONF_OPTS += \
	$(WPEWEBKIT_DEVEL_EXTRA_FLAGS) \
	$(WPEWEBKIT_DEVEL_FLAGS)

ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_SANDBOX),y)
WPEWEBKIT_DEVEL_CONF_OPTS += \
	-DENABLE_BUBBLEWRAP_SANDBOX=ON \
	-DBWRAP_EXECUTABLE=/usr/bin/bwrap \
	-DDBUS_PROXY_EXECUTABLE=/usr/bin/xdg-dbus-proxy
WPEWEBKIT_DEVEL_DEPENDENCIES += libseccomp
else
WPEWEBKIT_DEVEL_CONF_OPTS += -DENABLE_BUBBLEWRAP_SANDBOX=OFF
endif

ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_MULTIMEDIA),y)
WPEWEBKIT_DEVEL_CONF_OPTS += \
	-DENABLE_VIDEO=ON \
	-DENABLE_MEDIA_SOURCE=ON \
	-DENABLE_ENCRYPTED_MEDIA=ON \
	-DENABLE_THUNDER=ON \
	-DENABLE_WEB_AUDIO=ON
WPEWEBKIT_DEVEL_DEPENDENCIES += gstreamer1 gst1-libav gst1-plugins-base gst1-plugins-good wpeframework-clientlibraries
else
WPEWEBKIT_DEVEL_CONF_OPTS += \
	-DENABLE_VIDEO=OFF \
	-DENABLE_MEDIA_SOURCE=OFF \
	-DENABLE_ENCRYPTED_MEDIA=OFF \
	-DENABLE_THUNDER=OFF \
	-DENABLE_WEB_AUDIO=OFF
endif

ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_USE_GSTREAMER_GL),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_GSTREAMER_GL=ON
else
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_GSTREAMER_GL=OFF
endif

ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_WEBDRIVER),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DENABLE_WEBDRIVER=ON
else
WPEWEBKIT_DEVEL_CONF_OPTS += -DENABLE_WEBDRIVER=OFF
endif

ifeq ($(BR2_PACKAGE_WOFF2),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WOFF2=ON
WPEWEBKIT_DEVEL_DEPENDENCIES += woff2
else
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WOFF2=OFF
endif

# JIT is not supported for MIPS r6, but the WebKit build system does not
# have a check for these processors. Disable JIT forcibly here and use
# the CLoop interpreter instead.
#
# Upstream bug: https://bugs.webkit.org/show_bug.cgi?id=191258
ifeq ($(BR2_MIPS_CPU_MIPS32R6)$(BR2_MIPS_CPU_MIPS64R6),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DENABLE_JIT=OFF -DENABLE_C_LOOP=ON
endif

# Holepunch options.
ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_USE_PUNCH_HOLE_GSTREAMER),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_GSTREAMER_HOLEPUNCH=ON
else ifeq ($(BR2_PACKAGE_WPEWEBKIT_DEVEL_USE_PUNCH_HOLE_EXTERNAL),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_EXTERNAL_HOLEPUNCH=ON
endif

# Platform definitions.
ifeq ($(BR2_PACKAGE_WESTEROS),y)
WPEWEBKIT_DEVEL_DEPENDENCIES += westeros
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WPEWEBKIT_PLATFORM_WESTEROS=ON
ifeq ($(BR2_PACKAGE_WESTEROS_SINK),y)
WPEWEBKIT_DEVEL_DEPENDENCIES += westeros-sink
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WESTEROS_SINK=ON -DUSE_GSTREAMER_HOLEPUNCH=ON
else
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_GSTREAMER_HOLEPUNCH=OFF
endif
else ifeq ($(BR2_PACKAGE_HAS_NEXUS),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WPEWEBKIT_PLATFORM_BCM_NEXUS=ON
else ifeq ($(BR2_PACKAGE_HORIZON_SDK),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WPEWEBKIT_PLATFORM_INTEL_CE=ON
else ifeq ($(BR2_PACKAGE_INTELCE_SDK),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WPEWEBKIT_PLATFORM_INTEL_CE=ON
else ifeq ($(BR2_PACKAGE_RPI_FIRMWARE),y)
WPEWEBKIT_DEVEL_CONF_OPTS += -DUSE_WPEWEBKIT_PLATFORM_RPI=ON
endif


$(eval $(cmake-package))
