################################################################################
#
# wpeframework-doofah
#
################################################################################
WPEFRAMEWORK_DOOFAH_VERSION = 0b1f5ad9412ab5b7ab19d91059b01b7677547da9
WPEFRAMEWORK_DOOFAH_SITE = $(call github,Metrological,ThunderDoofah,$(WPEFRAMEWORK_DOOFAH_VERSION))
WPEFRAMEWORK_DOOFAH_INSTALL_STAGING = NO
WPEFRAMEWORK_DOOFAH_DEPENDENCIES = wpeframework

WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_DOOFAH_VERSION}

WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DLEGACY_CONFIG_GENERATOR=OFF

ifeq ($(BR2_CMAKE_HOST_DEPENDENCY),)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += \
       -DCMAKE_MODULE_PATH=$(HOST_DIR)/share/cmake/Modules
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_AUTOSTART),y)
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_AUTOSTART=true
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_CONNECTOR_CONFIG),"")
WPEFRAMEWORK_DOOFAH_CONF_OPTS += -DPLUGIN_DOOFAH_CONNECTOR_CONFIG=$(BR2_PACKAGE_WPEFRAMEWORK_DOOFAH_CONNECTOR_CONFIG)
endif

$(eval $(cmake-package))
