################################################################################
#
# wpeframework-cobalt
#
################################################################################

WPEFRAMEWORK_COBALT_VERSION = fbb0e5dd72baba9260b32b527e718bf95b8edea4
WPEFRAMEWORK_COBALT_SITE_METHOD = git
WPEFRAMEWORK_COBALT_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginCobalt.git
WPEFRAMEWORK_COBALT_INSTALL_STAGING = YES
WPEFRAMEWORK_COBALT_DEPENDENCIES = wpeframework

WPEFRAMEWORK_COBALT_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_COBALT_VERSION}

WPEFRAMEWORK_COBALT_CONF_OPTS += -DWPEFRAMEWORK_PLUGIN_COBALT_STARBOARD_CONFIGURATION_INCLUDE="starboard/wpe/rpi/configuration_public.h"

$(eval $(cmake-package))

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COBALT_AUTOSTART),y)
WPEFRAMEWORK_COBALT_CONF_OPTS += -DPLUGIN_COBALT_AUTOSTART=true
else
WPEFRAMEWORK_COBALT_CONF_OPTS += -DPLUGIN_COBALT_AUTOSTART=false
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_COBALT_OUTOFPROCESS),y)
WPEFRAMEWORK_COBALT_CONF_OPTS += -DPLUGIN_COBALT_OUTOFPROCESS=true
else
WPEFRAMEWORK_COBALT_CONF_OPTS += -DPLUGIN_COBALT_OUTOFPROCESS=false
endif
