#!/bin/sh
start() {
        echo -n "Starting display VC5 GEM driver: "
        insmod /lib/modules/brcmv3d.ko
        [ $? == 0 ] && echo "OK" || echo "FAIL"
}

stop() {
        echo -n "Stopping display VC5 GEM driver: "
        rmmod /lib/modules/brcmv3d.ko
        [ $? == 0 ] && echo "OK" || echo "FAIL"
}

restart() {
    stop
    start
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart|reload)
    restart
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?
