ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER),y)
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER=ON

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_NEXUS),y)
BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_IMPLEMENTATIONS += Nexus
WEBBRIDGE_DEPENDENCIES += bcm-refsw
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_STUB),y)
BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_IMPLEMENTATIONS += Stub
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_OUTOFPROCESS),y)
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_OUTOFPROCESS=true
else
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_OUTOFPROCESS=false
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_SERVICE_EXTERNAL),y)
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_SERVICE=external
else
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_SERVICE=internal
endif

ifeq ($(BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_AUTOTRACE),y)
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_AUTOTRACE=ON
else
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_AUTOTRACE=OFF
endif

WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_IMPLEMENTATION=${BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_IMPLEMENTATIONS}
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_IMPLEMENTATION_DEFAULT=${BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_IMPLEMENTATION_DEFAULT}
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_HARDWAREREADY=${BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_HARDWAREREADY}
WEBBRIDGE_CONF_OPTS += -DWEBBRIDGE_PLUGIN_RESOURCECENTER_SYSTEM=${BR2_PACKAGE_WEBBRIDGE_PLUGIN_RESOURCECENTER_SYSTEM}
endif
