################################################################################
#
# wpeframework-cryptography
#
################################################################################

WPEFRAMEWORK_CRYPTOGRAPHY_VERSION = 07b7b83d0060dc2e056d4dee0aa3efcaf2694c0f
WPEFRAMEWORK_CRYPTOGRAPHY_SITE_METHOD = git
WPEFRAMEWORK_CRYPTOGRAPHY_SITE = git@github.com:Metrological/cryptography.git
WPEFRAMEWORK_CRYPTOGRAPHY_INSTALL_STAGING = YES
WPEFRAMEWORK_CRYPTOGRAPHY_DEPENDENCIES = wpeframework

WPEFRAMEWORK_CRYPTOGRAPHY_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_CRYPTOGRAPHY_VERSION}

ifeq ($(WPEFRAMEWORK_CRYPTOGRAPHY_IMPL_THUNDER),y)
WPEFRAMEWORK_CRYPTOGRAPHY_CONF_OPTS += -DCRYPTOGAPHY_IMPLENTATION=Thunder
else ifeq ($(WPEFRAMEWORK_CRYPTOGRAPHY_IMPL_OPENSSL),y)
WPEFRAMEWORK_CRYPTOGRAPHY_CONF_OPTS += -DCRYPTOGAPHY_IMPLENTATION=OpenSSL
else ifeq ($(WPEFRAMEWORK_CRYPTOGRAPHY_IMPL_NEXUS),y)
WPEFRAMEWORK_CRYPTOGRAPHY_CONF_OPTS += -DCRYPTOGAPHY_IMPLENTATION=Nexus
endif

$(eval $(cmake-package))

