#!/bin/sh

SCRIPT_NAME="webbridge.sh"
BUMPER_SCRIPT=/NDS/bumper.sh
SOURCE=/NDS/metrological
HDD="`cat /tmp/diag`"

# Symlink /etc
ln -sfn $SOURCE/etc/playready /etc/playready
ln -sfn $SOURCE/etc/ssl /etc/ssl
ln -sfn $SOURCE/etc/fonts /etc/fonts

# Symlink /usr/lib
ln -sfn $SOURCE/usr/lib/gio /usr/lib/gio

# Symlink /usr/share
mkdir -p /usr/share/fonts
ln -sfn $SOURCE/usr/share/mime /usr/share/mime
ln -sfn $SOURCE/usr/share/X11 /usr/share/X11
ln -sfn $SOURCE/usr/share/fonts/ttf-bitstream-vera /usr/share/fonts/ttf-bitstream-vera

# Symlink /root
rm -rf $SOURCE/root
mkdir -p $HDD/app
ln -sfn $HDD/app $SOURCE/root

# Netflix
if [ ! -d $SOURCE/root/Netflix ]; then
	mkdir -p $SOURCE/root/Netflix/dpi
	ln -sfn /etc/playready $SOURCE/root/Netflix/dpi/playready
fi

# Firewall for non-prod builds
if [ -f /NDS/drivers/open_firewall_port.sh ]; then
	/NDS/drivers/open_firewall_port.sh tcp 80
	/NDS/drivers/open_firewall_port.sh tcp 9998
	/NDS/drivers/open_firewall_port.sh tcp 9536
fi

# Exports
export HOME=$SOURCE/root
export PATH=$SOURCE/usr/bin:/bin:/usr/bin
export GST_PLUGIN_PATH=$SOURCE/usr/lib/gstreamer-1.0
export GST_PLUGIN_SCANNER=$SOURCE/usr/libexec/gstreamer-1.0/gst-plugin-scanner
export LD_LIBRARY_PATH=$SOURCE/lib:$SOURCE/usr/lib:$SOURCE/usr/lib/gstreamer-1.0:/lib/:/usr/lib

LOOP=true
SLEEP=2
MAX_TRIES=60
TIMES_TRIED=0

# Internet
while $LOOP && [ $TIMES_TRIED -le $MAX_TRIES ]; do
    export TZ=$(wget -qO- http://jsonip.metrological.com | sed -e 's/^.*"tz":"\([^"]*\)".*$/\1/')
    ((TIMES_TRIED+=1))
    if [ "" != "$TZ" ]; then
		echo "${SCRIPT_NAME}: set timezone: $TZ"
        LOOP=false
    else
        sleep $SLEEP
    fi
done

# Clock
if [ -f /NDS/lib/libextClock.so ]; then
	# TOT
	LOOP=true
	TIMES_TRIED=0
	while $LOOP && [ $TIMES_TRIED -le $MAX_TRIES ]; do
	    ((TIMES_TRIED+=1))
	    if [ `LD_PRELOAD=/NDS/lib/libextClock.so date +"%Y"` -ge "2016" ]; then
			echo "${SCRIPT_NAME}: TOT found"
	        LOOP=false
	    else
	        sleep $SLEEP
	    fi
	done
	export LD_PRELOAD=/NDS/lib/libextClock.so
fi

# Shutdown all our processes in non stub version
if [ ! -f $SOURCE/NDS/webbridge-stub ]; then
	killall -9 rpcprocess
	killall -9 WPEWebProcess
	killall -9 WPENetworkProcess
	killall -9 WPEDatabaseProcess
	kill -9 $(ps | grep '/usr/bin/webbridge' | grep -v grep | awk '{print $1}')
fi

# Short sleep
sleep 3

# Bumper
if [ -f ${BUMPER_SCRIPT} ]; then
	${BUMPER_SCRIPT} 15 /NDS/config/bumper_ml.cfg &
fi

# WebBridge
if [ ! -f $SOURCE/NDS/webbridge-stub ]; then
	echo "${SCRIPT_NAME}: launching 'real' webbridge"
	$SOURCE/usr/bin/webbridge -c $SOURCE/etc/webbridge/config.json
else
	ACTIVEPROCESS=`ps | grep webbridge-stub | grep -v grep`
	if [ "x$ACTIVEPROCESS" == "x" ]; then
		echo "${SCRIPT_NAME}: launching 'stub' webbridge"
		$SOURCE/NDS/webbridge-stub
	else
		# ulimit for core dump
		mkdir -p $HOME/cores
		echo "$HOME/cores/core.%e.%p.%h.%t" > /proc/sys/kernel/core_pattern
		ulimit -c unlimited
		echo "${SCRIPT_NAME}: launching 'dev' webbridge"
		$SOURCE/usr/bin/webbridge -c $SOURCE/etc/webbridge/config.json
	fi
fi
