#!/bin/sh

start() {
	# Core dumps
	#echo 1 > /proc/sys/kernel/core_uses_pid
	#echo 2 > /proc/sys/fs/suid_dumpable
	#echo "/root/cores/core-pid_%p--process%E" > /proc/sys/kernel/core_pattern
	#mkdir -p /root/cores
	#ulimit -c unlimited
	mount -a

	if [ ! -d /root/Netflix/dpi ]; then
		mkdir -p /root/Netflix/dpi
		ln -sfn /etc/playready /root/Netflix/dpi/playready
	fi

        # No need for HDMI output
        /usr/bin/tvservice -o
	
	# needed for wayland/westeros/weston
	export XDG_RUNTIME_DIR=/tmp

	echo -n "Starting Bridge: "
	start-stop-daemon -S -q -b -m -p /var/run/bridge.pid --exec /usr/bin/bridge -- -b </dev/null >/dev/null 2>&1
	[ $? == 0 ] && echo "OK" || echo "FAIL"
}
stop() {
	echo -n "Stopping Bridge: "
	start-stop-daemon -K -q -p /var/run/bridge.pid
	[ $? == 0 ] && echo "OK" || echo "FAIL"
	rm -rf /var/run/bridge.pid
}
restart() {
	stop
	sleep 3
	start
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart|reload)
		restart
		;;
	*)
		echo "Usage: $0 {start|stop|restart}"
		exit 1
esac

exit $?
