################################################################################
#
# wpeframework-provisioning
#
################################################################################

WPEFRAMEWORK_PROVISIONING_VERSION = fcf6bbbfa5eb68cc3741f03b6b97759709eb234d
WPEFRAMEWORK_PROVISIONING_SITE_METHOD = git
WPEFRAMEWORK_PROVISIONING_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginProvisioning.git
WPEFRAMEWORK_PROVISIONING_INSTALL_STAGING = YES
WPEFRAMEWORK_PROVISIONING_DEPENDENCIES = wpeframework libprovision

WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_PROVISIONING_VERSION}

WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DWPEFRAMEWORK_PROVISIONING_URI=${BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_URI}
WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DPLUGIN_PROVISIONING_OPERATOR=${BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_OPERATOR}

ifeq ($(shell expr $(BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_PROVISIONING_CACHE_PERIODE) \> 0),1)
WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DPLUGIN_PROVISIONING_CACHE=$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_PROVISIONING_CACHE_PERIODE)) 
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_BLOBWRITER),y)
WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DPLUGIN_BLOBWRITER=ON
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_BLOBWRITER_BLOBS),)
WPEFRAMEWORK_PROVISIONING_CONF_OPTS += -DPLUGIN_BLOBWRITER_BLOBS="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PROVISIONING_BLOBWRITER_BLOBS))"
endif

$(eval $(cmake-package))
