ifeq ($(BR2_PACKAGE_BRIDGE_TEST_CYCLICINSPECTOR),y)
BRIDGE_CONF_OPTS += -DBRIDGE_TEST_CYCLICINSPECTOR=ON
endif

ifeq ($(BR2_PACKAGE_BRIDGE_TEST_LOADER),y)
BRIDGE_CONF_OPTS += -DBRIDGE_TEST_LOADER=ON
endif

ifeq ($(BR2_PACKAGE_BRIDGE_TEST_RPCLINK),y)
BRIDGE_CONF_OPTS += -DBRIDGE_TEST_RPCLINK=ON -DBRIDGE_RPC=ON
endif

ifeq ($(BR2_PACKAGE_TEST_LINUXONEWIRE),y)
BRIDGE_CONF_OPTS += -DTEST_LINUXONEWIRE=ON
endif

ifeq ($(BR2_PACKAGE_TEST_LINUXI2C),y)
BRIDGE_CONF_OPTS += -DTEST_LINUXI2C=ON
endif

ifeq ($(BR2_PACKAGE_TEST_LINUXSPI),y)
BRIDGE_CONF_OPTS += -DTEST_LINUXSPI=ON
endif

ifeq ($(BR2_PACKAGE_TEST_RASPIO),y)
BRIDGE_CONF_OPTS += -DTEST_RASPIO=ON
endif

ifeq ($(BR2_PACKAGE_BRIDGE_WARNING_REPORTING), y)
BRIDGE_CONF_OPTS += -DWARNING_REPORTING=ON
endif

ifeq ($(BR2_PACKAGE_BRIDGE_EXCEPTION_CATCHING), y)
BRIDGE_CONF_OPTS += -DEXCEPTION_CATCHING=ON
endif


